package snackBar;

public class Customer{
	private static int maxId =0;
	private int id;
	private String name;
	private double cashOnHand;

	public int getId(){
		return id;
	}

	public String getName(){
		return name;
	}

	public void String setName(String name){
		this.name = name;
	}

	public double getCashOnHand(){
		return cashOnHand;
	}

	public double void addCashOnHand(double cash){
		return cashOnHand += cashOnHand;
	}

	public void buySnacks(double totalCost){
		this.cashOnHand =+ totalCost
	}

}